Tidying up comments across all scripts
senecajs/repo-maintain pull request #1
Opened 2021-08-17 10:58 UTC by stokesriona

2021-08-18 16:27 UTC, rjrodger requested changes

2021-08-18 16:27 UTC, rjrodger commented on maintain.js
> +            // reading client's JSON files in
we only need to worry about the top level package.json file

2021-08-18 16:27 UTC, rjrodger commented on maintain.js
> +                        } else { // add in "else if" clause if searching for json value
prefer the style:
```
if() {
}
else if() {
}
else {
}
```

makes it easier to cut and paste if-else clauses

2021-08-18 16:30 UTC, merged

2021-08-19 11:58 UTC, stokesriona commented on maintain.js
> +            // reading client's JSON files in
That's changed now to only take the top level .json files, depending on future checks I may refactor how it's collecting the files in the first place

2021-08-19 12:44 UTC, stokesriona commented on maintain.js
> +                        } else { // add in "else if" clause if searching for json value
They're all split up now for this script, I'll do the same for the rest of the files in another cleanup branch